Resources:
  S3BucketDocuments:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3bucketName}
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            MaxAge: 3000